.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "DIST\-INFO" "8" "January 2020" "dist-base-files" "dist-base-files Manual"
.SH "NAME"
\fBdist\-info\fR \- output build version and build timestamp
.SH "SYNOPSIS"
\fBdist\-info\fR
.SH "DESCRIPTION"
Outputs build version and build timestamp\.
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
