#!/bin/bash

## Copyright (C) 2019 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

if [ "$sudo_password" = "" ]; then
   sudo_password="changeme"
fi

echo "$sudo_password"
